### ISSUE TITLE
[Bug]: Whitelist feature not working on Fabric

### ISSUE THREAD

**Issue by SaiCode-DHBW** [ErdbeerbaerLP/Discord-Chat-Integration#501]
### What happened?

A bug happened!

### Game Version

Other

### What platform are you using?

Fabric

### Platform version

0.14.10

### Config File

```toml
# General options for the bot
[general]
  # Insert your Bot Token here!
  # DO NOT SHARE IT WITH ANYONE!
  botToken = "*****"
  # The channel ID where the bot will be working in
  botChannel = "1041661009959596092"
  # The bot's status message
  # 
  # PLACEHOLDERS:
  # %online% - Online Players
  # %max% - Maximum Player Amount
  botStatusName = "%online% Spieler online"
  # Type of the bot's status
  # Allowed Values: DISABLED,PLAYING,WATCHING,LISTENING,STREAMING,COMPETING
  botStatusType = "PLAYING"
  # URL of the bot's stream when using the status type 'STREAMING'
  # Has to start with https://twitch.tv/ or https://www.youtube.com/watch?v=
  streamingURL = "https://discord.projektweihnachten.de/"
  # Enable checking for updates?
  # Notification will be shown after every server start in log when update is available
  enableUpdateChecker = true
  # The minimum release type for the update checker to notify
  # Allowed values: release, beta, alpha
  updateCheckerMinimumReleaseType = "beta"
  # Set to false to disable config migration from other mods/plugins to this one
  # This does not prevent updating of this config after mod updates
  allowConfigMigration = true
  # Attempt to parse id-based mentions to names in in-game chat
  parseMentionsIngame = true
  # Set to true to supress warning of unsafe mod download location
  ignoreFileSource = true
# Configuration options for commands
[commands]
  # The Role IDs of your Admin Roles
  # Now supports multiple roles which can access admin commands
adminRoleIDs = [  "1032666192701300758"  ]
  # Add your custom commands here
  # You can also generate some on https://erdbeerbaerlp.de/dcintegration-commands/
  # You must op this UUID in the ops.txt or some custom commands won't work!
  senderUUID = "1123ddf0-1e5f-4936-8aa6-ff2689261022"
  # Enable help command?
  # Disabling also removes response when you entered an invalid command
  # Requires server restart
  helpCmdEnabled = true
  # Enable the list command in discord
  # Requires server restart
  listCmdEnabled = true
  # Enable the uptime command in discord
  # Requires server restart
  uptimeCmdEnabled = true
  # Set to false to completely disable the "Unknown Command" message
  showUnknownCommandMessage = true
  # Set to true to enable the "Unknown Command" message in all channels
  showUnknownCommandEverywhere = false

    [[commands.customCommands]]
      name = "kick"
      description = "Kicks an player from the Server"
      mcCommand = "kick %player% %reason%"
      textToSend = ""
      adminOnly = true
      hidden = false

        [[commands.customCommands.args]]
          name = "player"
          description = "The player to be kicked"
          optional = false

        [[commands.customCommands.args]]
          name = "reason"
          description = "Reason for the kick"
          optional = true

    [[commands.customCommands]]
      name = "stop"
      description = "Stops the server"
      mcCommand = "stop"
      textToSend = ""
      adminOnly = true
      hidden = false
args = [    ]

    [[commands.customCommands]]
      name = "kill"
      description = "Kills an Player or Entity"
      mcCommand = "kill %target%"
      textToSend = ""
      adminOnly = true
      hidden = false

        [[commands.customCommands.args]]
          name = "target"
          description = "The target(s) for the kill command."
          optional = false
# Toggle some message related features
[messages]
  # Changing this to an language key (like en-US, de-DE) will always attempt to download the latest language file from https://github.com/ErdbeerbaerLP/Discord-Integration-Translations
  # Setting to 'local' disables downloading
  language = "de-DE"
  # Enable formatting conversion (Markdown <==> Minecraft)
  convertCodes = true
  # Send formatting codes from mc chat to discord
  # Has no effect when markdown <==> Minecraft is enabled
  formattingCodesToDiscord = true
  # Should /say output be sent to discord?
  sendOnSayCommand = true
  # Should /me output be sent to discord?
  sendOnMeCommand = true
  # When an /say command's message starts with this prefix, it will not be sent to discord
  sayCommandIgnoredPrefix = "§4§6§k§r"
  # Should tamed entity death be visible in discord?
  sendDeathMessagesForTamedAnimals = false
# Advanced options
[advanced]
  # Custom channel ID for server specific messages (like Join/leave)
  # Leave 'default' to use default channel
  serverChannelID = "default"
  # Custom channel ID for death messages
  # Leave 'default' to use default channel
  deathsChannelID = "default"
  # Custom channel for for ingame messages
  # Leave 'default' to use default channel
  chatOutputChannelID = "default"
  # Custom channel where messages get sent to minecraft
  # Leave 'default' to use default channel
  chatInputChannelID = "default"
  # Allows you to change the target URL for the API to make it usable with custom discord instances like fosscord
  # DO NOT CHANGE if you don't know what you are doing!!
  baseAPIUrl = "https://discord.com"
# Config options which only have an effect when using forge
[forgeSpecific]
  # A list of blacklisted modids
  # Adding one will prevent the mod to send messages to discord using forges IMC system
IMC_modIdBlacklist = [  "examplemod"  ]
  # Show item information, which is visible on hover ingame, as embed in discord?
  sendItemInfo = true
# Configuration for linking
[linking]
  # Unlink players when they leave the discord server for whatever reason (ex. leave,kick,ban)?
  unlinkOnLeave = true
  # Should discord linking be enabled?
  # If whitelist is on, this can NOT be disabled
  # DOES NOT WORK IN OFFLINE MODE!
  enableLinking = true
  # Set Discord nicknames to match Minecraft usernames when linked
  shouldNickname = false
  # Role ID of an role an player should get when he links his discord account
  # Leave as 0 to disable
  linkedRoleID = "1039090701587193856"
  # Enable discord based whitelist?
  # This will override the link config!
  # To whitelist use the whitelist command in the bot DMs
  whitelistMode = true
  # Adding Role IDs here will require the players to have at least ONE of these roles to link account
requiredRoles = [  "1032666192676139132"  ]
  # Adding setting keys to this array will prevent thoose settings to be changed
  # They will still show up in the list though
settingsBlacklist = [    ]

    # Allows you to configure the default values of some personal settings
    [linking.personalSettingsDefaults]
      default_useDiscordNameInChannel = true
      default_ignoreReactions = false
      default_pingSound = true
# Webhook configuration
[webhook]
  # Whether or not the bot should use a webhook (it will create one)
  enable = true
  # The avatar to be used for server messages
  serverAvatarURL = "https://cdn.discordapp.com/avatars/1041662688239030352/561fd04779ed27abb66ce09d0afc0528.png"
  # The name to be used for server messages
  serverName = "Minecraft Server"
  # The URL where the player avatar gets fetched from
  # 
  # PLACEHOLDERS:
  # %uuid% - Returns the player's UUID with dashes
  # %uuid_dashless% - Returns the player's UUID without dashes
  # %name% - Returns the player's name
  # %randomUUID% - Returns an random UUID which can be used to prevent discord cache
  playerAvatarURL = "https://visage.surgeplay.com/bust/%uuid%.png?randomuuid=%randomUUID%"
  webhookName = "Minecraft Server"
# Configuration for the in-game command '/discord'
[ingameCommand]
  # Enable the /discord command to show an custom message with invite URL?
  enabled = true
  # The message displayed when typing /discord in the server chat
  message = "Du brauchst den Dicord link? https://discord.projektweihnachten.de/"
  # The message shown when hovering the /discord command message
  hoverMessage = "Klicke um den Link zu öffnen"
  # The url to open when clicking the /discord command text
  inviteURL = "https://discord.projektweihnachten.de/"
# The command log channel is an channel where every command execution gets logged
[commandLog]
  # Channel ID for the command log channel
  # Leave 0 to disable
  channelID = "1041664979843158086"
  # The format of the log messages
  # 
  # PLACEHOLDERS:
  # %sender% - The name of the Command Source
  # %cmd% - executed command (e.g. "say Hello World"
  # %cmd-no-args% - Command without arguments (e.g. "say"
  message = "%sender%: `%cmd%`"
  # A list of commands that should NOT be logged
ignoredCommands = [    ]
# Configure votifier integration here
# (Spigot only)
[votifier]
  # Should votifier messages be sent to discord?
  enabled = false
  # Custom channel ID for Votifier messages
  # Leave 'default' to use default channel
  votifierChannelID = "default"
  # The message format of the votifier message
  # 
  # PLACEHOLDERS:
  # %player% - The player´s name
  # %site% - The name of the vote site
  # %addr% - (IP) Address of the site
  message = ":ballot_box: %player% just voted on %site%"
  # Name of the webhook title
  name = "Votifier"
  # URL of the webhook avatar image
  avatarURL = "https://www.cubecraft.net/attachments/bkjvmqn-png.126824/"
# Configure Dynmap integration here
[dynmap]
  # The message format of the message forwarded to discord
  # 
  # PLACEHOLDERS:
  # %sender% - The sender´s name
  # %msg% - The Message
  dcMessage = "<%sender%> %msg%"
  # Custom channel ID for dynmap chat
  # Leave 'default' to use default channel
  dynmapChannelID = "default"
  # Name of the webhook title
  name = "Dynmap Web-Chat"
  # URL of the webhook avatar image
  avatarURL = "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/91/Map_Zoom_0.png/revision/latest?cb=20200311153330"
  # The name format of the message forwarded to the dynmap webchat
  # 
  # PLACEHOLDERS:
  # %name% - The discord name of the sender (including nickname)
  # %name#tag% - The discord name with tag of the sender (without nickname)
  webName = "%name% (discord)"
  # Name shown in discord when no name was specified on the website
  unnamed = "Unnamed"
# Configure some plugin-specific BStats settings here
# Everything can be seen here: https://bstats.org/plugin/bukkit/DiscordIntegration/9765
# 
# Does not apply to fabric yet, as there is no bstats for it
[bstats]
  # Allow sending of installed addon stats (Name and version of installed addons)
  sendAddonStats = true
# Settings for servers running as Bungeecord-suberver
[bungee]
  # Set this to true if the server is running as an subserver of an bungeecord network and therefore needs to be in offline mode
  # Setting this will force account linking in offline mode
  # Do NOT use for actual offline mode servers, as this will break the linking feature because of the UUIDs!
  # 
  # Currently no support for floodgate running on bungee
  isBehindBungee = false
```

### Crash report / Error log (if applicable)

```shell
-
```

### Additional Information

Minecraft 1.19.2 (not a valid option)
![image](https://user-images.githubusercontent.com/99813121/201660980-9821618b-1a17-4c76-8201-ba7fe6253f0e.png)
Kicking the user works,
![image](https://user-images.githubusercontent.com/99813121/201661145-ba5721ae-9b62-42e2-8c9b-a3ee7eee3840.png)
/ commands not listed
![image](https://user-images.githubusercontent.com/99813121/201661226-490fe9d4-622f-4b25-9238-576d05c40f87.png)
But synced, so registered

(and btw i would like to change https://discord.gg/someserver to a real invite link)
